// this is vanilla javascript
// this is generated by postman

var requestOptions = {
    method: 'GET',
    redirect: 'follow'
  };
  
  fetch("localhost:3000/getData", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));